version: '3.7'

services:
  footage:
    build: ./backend/footage
    #command: python manage.py runserver 0.0.0.0:8001
    command: gunicorn footage.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - ./backend/footage:/usr/src/app/
    ports:
      - 8001:8001
    env_file:
      - ./backend/footage/.env.dev
    depends_on:
      - footage-db

  footage-db:
    build: ./databases/footage
    volumes:
      - ./databases/footage/backup:/cron/backups/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=footage_dev
      - PGUSER=admin

  #footage-db-test:
  #  image: postgres:12-alpine
  #  environment:
  #    - POSTGRES_USER=admin
  #    - POSTGRES_PASSWORD=password
  #    - POSTGRES_DB=footage_dev
  #    - PGUSER=admin

  user:
    build: ./backend/user
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./backend/user:/usr/src/app/
    ports:
      - 8002:8002
    env_file:
      - ./backend/user/.env.dev
    depends_on: 
      - mysql-db

  mysql-db:
    build: ./databases/user
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases/user/backup:/cron/backups/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret_pass
      - MYSQL_DATABASE=mysql_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pass1234

  readings:
    build: ./backend/readings
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - ./backend/readings:/usr/src/app/
    ports:
      - 8003:8003
    env_file:
      - ./backend/readings/.env.dev
    depends_on: 
      - mysql-db

  webgateway:
    build: ./backend/webgateway
    command: python manage.py runserver 0.0.0.0:8004
    #command: gunicorn proj_webgateway.wsgi:application --bind 0.0.0.0:8004
    volumes:
      - ./backend/webgateway:/usr/src/app/
    ports:
      - 8004:8004
    env_file:
      - ./backend/webgateway/.env.dev
    depends_on: 
      - mysql-webgateway-db

  mysql-webgateway-db:
    build: ./databases/webgateway
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases/webgateway/backup:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret_pass
      - MYSQL_DATABASE=apigateway_dev
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password