# Generated by Django 3.1.2 on 2020-10-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('port', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='api',
            name='upstream_url',
        ),
        migrations.AddField(
            model_name='api',
            name='origin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='apigateway.proyect'),
            preserve_default=False,
        ),
    ]
