# Generated by Django 3.1.2 on 2020-10-08 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apigateway', '0002_auto_20201008_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apigateway.proyect'),
        ),
    ]
